import { Terminal, AlertTriangle, Play, ChevronDown, ChevronRight, Sparkles, Cpu, Download, HelpCircle } from 'lucide-react';
import { useState, useEffect, useRef } from 'react';
import { api } from '@/lib/api';

const SUSPICIOUS_PATTERNS = [
  'wget ', 'curl ', 'chmod +x', 'base64', ' nc ', 'nmap', 'aws ', 'kubectl',
  'docker', '.ssh', '/etc/shadow', '/etc/passwd', 'python3 -c', 'python -c',
  '/bin/sh', '/bin/bash', 'exec(', 'eval(', 'reverse', 'backdoor',
];

function isSuspiciousCmd(cmd: string): boolean {
  const lower = cmd.toLowerCase();
  return SUSPICIOUS_PATTERNS.some(p => lower.includes(p));
}

const SOURCE_META: Record<string, { label: string; icon: React.ElementType; className: string; title: string }> = {
  ai: {
    label: 'AI',
    icon: Sparkles,
    className: 'bg-violet-500/10 border-violet-500/30 text-violet-400',
    title: 'Response generated by DeepSeek LLM (ai-engine)',
  },
  static: {
    label: 'SIM',
    icon: Cpu,
    className: 'bg-slate-700/60 border-slate-600/40 text-slate-500',
    title: 'Pre-built honeypot simulation response',
  },
  malware: {
    label: 'DL',
    icon: Download,
    className: 'bg-orange-500/10 border-orange-500/30 text-orange-400',
    title: 'Malware/payload download detected — submitted to VirusTotal',
  },
  fallback: {
    label: 'ERR',
    icon: HelpCircle,
    className: 'bg-slate-700/40 border-slate-700/40 text-slate-600',
    title: 'Unknown command — fallback response',
  },
};

function SourceBadge({ source }: { source?: string }) {
  const meta = SOURCE_META[source ?? 'static'] ?? SOURCE_META.static;
  const Icon = meta.icon;
  return (
    <span
      title={meta.title}
      className={`shrink-0 inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded border text-[10px] font-mono font-semibold tracking-widest select-none ${meta.className}`}
    >
      <Icon className="w-2.5 h-2.5" />
      {meta.label}
    </span>
  );
}

function CommandLine({ cmd, index, isNew }: { cmd: any; index: number; isNew: boolean }) {
  const [expanded, setExpanded] = useState(true);
  const suspicious = isSuspiciousCmd(cmd.command);
  const hasOutput = cmd.output && cmd.output.trim().length > 0;
  const outputLines = hasOutput ? (cmd.output as string).split('\n') : [];
  const isLong = outputLines.length > 12;
  const [showAll, setShowAll] = useState(false);
  const displayedLines = isLong && !showAll ? outputLines.slice(0, 12) : outputLines;

  return (
    <div
      className={`rounded border transition-all ${
        suspicious
          ? 'border-red-500/30 bg-red-500/5'
          : 'border-transparent'
      } ${isNew ? 'animate-in fade-in' : ''}`}
    >
      {/* Command row */}
      <div
        className={`flex items-start gap-2 px-2 py-1 rounded-t cursor-pointer select-text group ${
          suspicious ? 'hover:bg-red-500/8' : 'hover:bg-slate-800/40'
        }`}
        onClick={() => hasOutput && setExpanded(o => !o)}
      >
        <span className="text-slate-600 text-xs shrink-0 pt-0.5 w-14 text-right font-mono">
          {new Date(cmd.timestamp).toLocaleTimeString('en-GB', { hour12: false })}
        </span>
        <span className="text-slate-500 shrink-0 pt-0.5">#</span>
        {suspicious && <AlertTriangle className="w-3.5 h-3.5 text-red-400 shrink-0 mt-0.5" />}
        <span className={`flex-1 font-mono text-sm break-all ${
          suspicious ? 'text-red-300' : 'text-emerald-400'
        }`}>
          {cmd.command}
        </span>
        <SourceBadge source={cmd.response_source} />
        {hasOutput && (
          <span className="text-slate-600 group-hover:text-slate-400 shrink-0 mt-0.5 transition-colors">
            {expanded
              ? <ChevronDown className="w-3.5 h-3.5" />
              : <ChevronRight className="w-3.5 h-3.5" />}
          </span>
        )}
      </div>

      {/* Output block */}
      {hasOutput && expanded && (
        <div className="ml-16 pl-2 border-l border-slate-700/50 mb-1 mr-2">
          <pre className="text-xs font-mono text-slate-400 whitespace-pre-wrap break-all leading-5">
            {displayedLines.join('\n')}
          </pre>
          {isLong && (
            <button
              onClick={e => { e.stopPropagation(); setShowAll(v => !v); }}
              className="text-xs text-cyan-500 hover:text-cyan-400 mt-1"
            >
              {showAll ? '▲ show less' : `▼ ${outputLines.length - 12} more lines`}
            </button>
          )}
        </div>
      )}

      {/* Exit-code badge for non-zero */}
      {cmd.exit_code !== undefined && cmd.exit_code !== 0 && cmd.exit_code !== null && (
        <div className="ml-16 mb-1">
          <span className="text-xs text-red-400/70 font-mono">exit {cmd.exit_code}</span>
        </div>
      )}
    </div>
  );
}

interface SessionPlaybackProps {
  sessionId: string | null;
}

export function SessionPlayback({ sessionId }: SessionPlaybackProps) {
  const [commands, setCommands] = useState<any[]>([]);
  const [prevCount, setPrevCount] = useState(0);
  const [isReplaying, setIsReplaying] = useState(false);
  const [replayIndex, setReplayIndex] = useState(0);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!sessionId) return;
    const fetchCommands = async () => {
      try {
        const res = await api.get(`/api/sessions/${sessionId}/commands`);
        const fetched = res.data.commands || [];
        setPrevCount(c => { setPrevCount(fetched.length); return c; });
        setCommands(fetched);
      } catch (err) {
        console.error('Failed to fetch session commands', err);
      }
    };
    fetchCommands();
    const interval = setInterval(fetchCommands, 5000);
    return () => clearInterval(interval);
  }, [sessionId]);

  // Auto-scroll to bottom when new commands arrive (live session)
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [commands.length]);

  const handleReplay = () => {
    if (commands.length === 0) return;
    setIsReplaying(true);
    setReplayIndex(0);
  };

  useEffect(() => {
    if (!isReplaying) return;
    if (replayIndex < commands.length) {
      const timer = setTimeout(() => setReplayIndex(p => p + 1), 800);
      return () => clearTimeout(timer);
    } else {
      const timer = setTimeout(() => setIsReplaying(false), 1500);
      return () => clearTimeout(timer);
    }
  }, [isReplaying, replayIndex, commands.length]);

  const displayedCommands = isReplaying ? commands.slice(0, replayIndex) : commands;
  const suspiciousCount = commands.filter(c => isSuspiciousCmd(c.command)).length;

  return (
    <div className="bg-slate-900 rounded-lg border border-slate-800 overflow-hidden flex flex-col">
      <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between gap-4 flex-wrap shrink-0">
        <div className="flex items-center gap-3">
          <Terminal className="w-5 h-5 text-emerald-400" />
          <h2 className="text-slate-100">Terminal Replay</h2>
          <span className="text-xs text-slate-500 font-mono">{sessionId?.slice(0, 8) ?? 'No session'}</span>
          {suspiciousCount > 0 && (
            <span className="flex items-center gap-1 px-2 py-0.5 text-xs bg-red-500/10 border border-red-500/20 text-red-400 rounded">
              <AlertTriangle className="w-3 h-3" />
              {suspiciousCount} suspicious
            </span>
          )}
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-slate-500">{commands.length} commands</span>
          <button
            onClick={handleReplay}
            disabled={isReplaying || commands.length === 0}
            className={`flex items-center gap-2 px-3 py-1.5 rounded text-xs transition-colors border ${
              isReplaying || commands.length === 0
                ? 'bg-slate-800 border-slate-700 text-slate-500 cursor-not-allowed'
                : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-emerald-500/40 hover:text-emerald-400'
            }`}
          >
            <Play className={`w-3 h-3 ${isReplaying ? 'animate-pulse text-emerald-400' : ''}`} />
            {isReplaying ? 'Replaying…' : 'Replay'}
          </button>
        </div>
      </div>

      {/* Terminal body */}
      <div className="flex-1 overflow-auto p-4 bg-slate-950 min-h-[320px] max-h-[520px] font-mono text-sm">
        {!sessionId ? (
          <div className="flex h-full items-center justify-center text-slate-600 text-sm">
            Select a session to view the terminal replay
          </div>
        ) : commands.length === 0 ? (
          <div className="flex h-full items-center justify-center text-slate-600 text-sm">
            No commands recorded for this session
          </div>
        ) : (
          <div className="space-y-0.5">
            {displayedCommands.map((cmd, idx) => (
              <CommandLine
                key={cmd.sequence_number ?? idx}
                cmd={cmd}
                index={idx}
                isNew={idx >= prevCount - 1}
              />
            ))}
            <div ref={bottomRef} />
          </div>
        )}
      </div>

      <div className="px-6 py-2.5 border-t border-slate-800 bg-slate-900 flex items-center justify-between text-xs gap-4 flex-wrap">
        <span className="text-slate-500">
          <span className="text-slate-300">{commands.length}</span> commands · click any row to toggle output
        </span>
        <div className="flex items-center gap-3 text-[10px]">
          {Object.entries(SOURCE_META).map(([key, m]) => {
            const Icon = m.icon;
            return (
              <span key={key} title={m.title} className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded border font-mono font-semibold tracking-widest ${m.className}`}>
                <Icon className="w-2.5 h-2.5" />{m.label}
              </span>
            );
          })}
          <span className="text-slate-600">= response source</span>
        </div>
      </div>
    </div>
  );
}
